_category: market
_path: ./strategies_repo\market\local_freqtrade_InformativeSample
archived_date: '2026-05-26'
archived_reason: Freqtrade加密策略，不适合A股
archived_tags:
- archived:passed
archived_tier: archived
created: '2026-05-23'
description: 'Sample strategy implementing Informative Pairs - compares stake_currency
  with USDT.

  Not performing very well - but should serve as an example how to use a referential
  pair against USDT.

  author@: xmatt'
last_backtest: null
metrics:
  annual_return: null
  drawdown: null
  sharpe: null
  total_trades: null
  win_rate: null
name: local_freqtrade_InformativeSample
params: {}
source: 本地-freqtrade
source_url: https://github.com/freqtrade/freqtrade-strategies
tags:
- local
- freqtrade
- 均线
- ML
type: unknown
