_category: market
_path: ./strategies_repo\market\local_freqtrade_CustomStoplossWithPSAR
archived_date: '2026-05-26'
archived_reason: Freqtrade加密策略，不适合A股
archived_tags:
- archived:passed
archived_tier: archived
created: '2026-05-23'
description: 'this is an example class, implementing a PSAR based trailing stop loss

  you are supposed to take the `custom_stoploss()` and `populate_indicators()`

  parts and adapt it to your own strategy


  the populat'
last_backtest: null
metrics:
  annual_return: null
  drawdown: null
  sharpe: null
  total_trades: null
  win_rate: null
name: local_freqtrade_CustomStoplossWithPSAR
params: {}
source: 本地-freqtrade
source_url: https://github.com/freqtrade/freqtrade-strategies
tags:
- local
- freqtrade
- 止损
- ML
type: unknown
