_category: market
_path: ./strategies_repo\market\local_freqtrade_FixedRiskRewardLoss
archived_date: '2026-05-26'
archived_reason: Freqtrade加密策略，不适合A股
archived_tags:
- archived:passed
archived_tier: archived
created: '2026-05-23'
description: 'This strategy uses custom_stoploss() to enforce a fixed risk/reward
  ratio

  by first calculating a dynamic initial stoploss via ATR - last negative peak


  After that, we caculate that initial risk and mu'
last_backtest: null
metrics:
  annual_return: null
  drawdown: null
  sharpe: null
  total_trades: null
  win_rate: null
name: local_freqtrade_FixedRiskRewardLoss
params: {}
source: 本地-freqtrade
source_url: https://github.com/freqtrade/freqtrade-strategies
tags:
- local
- freqtrade
- 止损
type: unknown
